/* This file is generated by scripts/generate-public-asset-manifest.mjs. */
/* Do not edit it directly. Change source assets or the generator instead. */

export const generatedPublicAssetDefinitions = [
  {
    "logicalPath": "/public-assets/public-site.css",
    "versionedPath": "/public-assets/833e433b0ca31719/public-site.css",
    "fileName": "public-site.css",
    "versionedFileName": "833e433b0ca31719/public-site.css",
    "contentType": "text/css; charset=utf-8",
    "contentHash": "833e433b0ca31719"
  },
  {
    "logicalPath": "/public-assets/public-site.js",
    "versionedPath": "/public-assets/46973d85f0a28806/public-site.js",
    "fileName": "public-site.js",
    "versionedFileName": "46973d85f0a28806/public-site.js",
    "contentType": "text/javascript; charset=utf-8",
    "contentHash": "46973d85f0a28806"
  },
  {
    "logicalPath": "/public-assets/swooshz-mark.png",
    "versionedPath": "/public-assets/5a272d5bd2ef8ad6/swooshz-mark.png",
    "fileName": "swooshz-mark.png",
    "versionedFileName": "5a272d5bd2ef8ad6/swooshz-mark.png",
    "contentType": "image/png",
    "contentHash": "5a272d5bd2ef8ad6"
  },
  {
    "logicalPath": "/public-assets/hero-monument-640.avif",
    "versionedPath": "/public-assets/197aee0519e60060/hero-monument-640.avif",
    "fileName": "hero-monument-640.avif",
    "versionedFileName": "197aee0519e60060/hero-monument-640.avif",
    "contentType": "image/avif",
    "contentHash": "197aee0519e60060"
  },
  {
    "logicalPath": "/public-assets/hero-monument-960.avif",
    "versionedPath": "/public-assets/f9af60255ab06136/hero-monument-960.avif",
    "fileName": "hero-monument-960.avif",
    "versionedFileName": "f9af60255ab06136/hero-monument-960.avif",
    "contentType": "image/avif",
    "contentHash": "f9af60255ab06136"
  },
  {
    "logicalPath": "/public-assets/hero-monument-1280.avif",
    "versionedPath": "/public-assets/38b64c1ffa708f6e/hero-monument-1280.avif",
    "fileName": "hero-monument-1280.avif",
    "versionedFileName": "38b64c1ffa708f6e/hero-monument-1280.avif",
    "contentType": "image/avif",
    "contentHash": "38b64c1ffa708f6e"
  },
  {
    "logicalPath": "/public-assets/hero-monument-1672.avif",
    "versionedPath": "/public-assets/445a33e448ccd282/hero-monument-1672.avif",
    "fileName": "hero-monument-1672.avif",
    "versionedFileName": "445a33e448ccd282/hero-monument-1672.avif",
    "contentType": "image/avif",
    "contentHash": "445a33e448ccd282"
  },
  {
    "logicalPath": "/public-assets/hero-monument-640.webp",
    "versionedPath": "/public-assets/ba4b718a6694edcf/hero-monument-640.webp",
    "fileName": "hero-monument-640.webp",
    "versionedFileName": "ba4b718a6694edcf/hero-monument-640.webp",
    "contentType": "image/webp",
    "contentHash": "ba4b718a6694edcf"
  },
  {
    "logicalPath": "/public-assets/hero-monument-960.webp",
    "versionedPath": "/public-assets/b1ead53875530edc/hero-monument-960.webp",
    "fileName": "hero-monument-960.webp",
    "versionedFileName": "b1ead53875530edc/hero-monument-960.webp",
    "contentType": "image/webp",
    "contentHash": "b1ead53875530edc"
  },
  {
    "logicalPath": "/public-assets/hero-monument-1280.webp",
    "versionedPath": "/public-assets/8fca037b2db0efc8/hero-monument-1280.webp",
    "fileName": "hero-monument-1280.webp",
    "versionedFileName": "8fca037b2db0efc8/hero-monument-1280.webp",
    "contentType": "image/webp",
    "contentHash": "8fca037b2db0efc8"
  },
  {
    "logicalPath": "/public-assets/hero-monument-1672.webp",
    "versionedPath": "/public-assets/14ab7f6795f2e5a4/hero-monument-1672.webp",
    "fileName": "hero-monument-1672.webp",
    "versionedFileName": "14ab7f6795f2e5a4/hero-monument-1672.webp",
    "contentType": "image/webp",
    "contentHash": "14ab7f6795f2e5a4"
  },
  {
    "logicalPath": "/public-assets/hero-monument-640.png",
    "versionedPath": "/public-assets/9e4948ec50a2f4fc/hero-monument-640.png",
    "fileName": "hero-monument-640.png",
    "versionedFileName": "9e4948ec50a2f4fc/hero-monument-640.png",
    "contentType": "image/png",
    "contentHash": "9e4948ec50a2f4fc"
  },
  {
    "logicalPath": "/public-assets/hero-monument-1280.png",
    "versionedPath": "/public-assets/d34ad0355686914d/hero-monument-1280.png",
    "fileName": "hero-monument-1280.png",
    "versionedFileName": "d34ad0355686914d/hero-monument-1280.png",
    "contentType": "image/png",
    "contentHash": "d34ad0355686914d"
  },
  {
    "logicalPath": "/public-assets/fonts/manrope-latin-variable.woff2",
    "versionedPath": "/public-assets/a30ddcd349703aff/fonts/manrope-latin-variable.woff2",
    "fileName": "fonts/manrope-latin-variable.woff2",
    "versionedFileName": "a30ddcd349703aff/fonts/manrope-latin-variable.woff2",
    "contentType": "font/woff2",
    "contentHash": "a30ddcd349703aff"
  },
  {
    "logicalPath": "/public-assets/fonts/fraunces-italic-latin-variable.woff2",
    "versionedPath": "/public-assets/066710ce7ed235a3/fonts/fraunces-italic-latin-variable.woff2",
    "fileName": "fonts/fraunces-italic-latin-variable.woff2",
    "versionedFileName": "066710ce7ed235a3/fonts/fraunces-italic-latin-variable.woff2",
    "contentType": "font/woff2",
    "contentHash": "066710ce7ed235a3"
  }
] as const;

const publicAssetUrlByLogicalPath = new Map<string, string>(
  generatedPublicAssetDefinitions.map((asset) => [asset.logicalPath, asset.versionedPath]),
);

export function publicAssetUrl(logicalPath: string): string {
  const versionedPath = publicAssetUrlByLogicalPath.get(logicalPath);

  if (!versionedPath) {
    throw new Error(`Unknown public asset: ${logicalPath}`);
  }

  return versionedPath;
}
